### ISSUE TITLE
Limma dependency causes failure to load

### ISSUE THREAD

**Issue by ESPoppelaars** [stamats/MKmisc#2]
Dependency package 'limma' has been removed from CRAN and older versions require R <= 2.5.1. Therefore, I cannot load MKmisc anymore with my R version 3.5.1. Can this be solved please? Is there a workaround in the meantime?
Thank you in advance!

**Comment by ESPoppelaars** [comment]
Sorry, I realized that there is a workaround available (via http://bioconductor.org/packages/release/bioc/html/limma.html), although CRAN does not mention this:

if (!requireNamespace("BiocManager", quietly = TRUE))
    install.packages("BiocManager")
BiocManager::install("limma")

**Comment by LukasWallrich** [comment]
Could this workaround be included in the failure message? Or at least in the package README? As it stands, it's a bit unfortunate to have to read closed issues to be able to use this very helpful package.

**Comment by stamats** [comment]
I have added it to the README file. In addition, I would like to mention that I have split MKmisc into several packages with different functionalities. Nevertheless, I will of course further maintain it and correct bugs.
Matthias
