### ISSUE TITLE
mice and mi.t.test 

### ISSUE THREAD

**Issue by atanasj** [stamats/MKmisc#4]
Is it possible to use the `mi.t.test` function with `mice`? See [here](https://stackoverflow.com/questions/73323019/mice-paired-sample-t-test-and-cohens-d-estimation-using-imputed-datasets).

**Comment by stamats** [comment]
Yes, it is possible. You need package miceadds. I would also ask you to switch to package MKinfer.

library(mice)
library(miceadds)
library(MKinfer)

## Generate some data
set.seed(123)
x <- rnorm(25, mean = 1)
x[sample(1:25, 5)] <- NA
y <- rnorm(20, mean = -1)
y[sample(1:20, 4)] <- NA
pair <- c(rnorm(25, mean = 1), rnorm(20, mean = -1))
g <- factor(c(rep("yes", 25), rep("no", 20)))
D <- data.frame(ID = 1:45, variable = c(x, y), pair = pair, group = g)

## impute with mice
res.mice <- mice(D)

## convert mids object to datalist
res.list <- mids2datlist(res.mice)

## perform t-test
mi.t.test(res.list, x = "variable", y = "group")


Best Matthias

**Comment by atanasj** [comment]
Thanks @stamats!
